### ISSUE TITLE
convert bangladesh tracing guide to structure here

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/tracing-guides#20]
https://wiki.openstreetmap.org/wiki/User:Geocruizer

**Comment by Geocruizer** [comment]
![homesteadwaterbody](https://cloud.githubusercontent.com/assets/4990708/6394964/2cbafea0-bda3-11e4-800b-e71e69829622.PNG)
![homesteadwaterbody_notrace](https://cloud.githubusercontent.com/assets/4990708/6394965/2f242f36-bda3-11e4-8bad-d4663c16365a.PNG)

**Comment by Geocruizer** [comment]
![river_area](https://cloud.githubusercontent.com/assets/4990708/6395711/e3938f58-bda7-11e4-8a2f-bd796d18607c.PNG)
![river_notrace](https://cloud.githubusercontent.com/assets/4990708/6395716/e68f55de-bda7-11e4-9553-e684324ea656.PNG)

**Comment by Geocruizer** [comment]
![ditch](https://cloud.githubusercontent.com/assets/4990708/6421057/87f35406-be99-11e4-9e9d-d35a60a931ad.PNG)
![ditch_notrace](https://cloud.githubusercontent.com/assets/4990708/6421058/89e26ae0-be99-11e4-94fb-7cb54a5c28b8.PNG)

**Comment by Geocruizer** [comment]
![localroad](https://cloud.githubusercontent.com/assets/4990708/6477410/9806fdb0-c1f1-11e4-9546-945fe7dbb844.PNG)
![localroad_notrace](https://cloud.githubusercontent.com/assets/4990708/6477417/a3f33012-c1f1-11e4-963a-d7a8c745b5af.PNG)

**Comment by Geocruizer** [comment]
![greentrace](https://cloud.githubusercontent.com/assets/4990708/6589781/260e6910-c77c-11e4-9d70-b6f8b0dd3895.PNG)
![greenroad](https://cloud.githubusercontent.com/assets/4990708/6589785/53ab5e5a-c77c-11e4-99e4-ead5818b8a6f.PNG)

**Comment by Geocruizer** [comment]
![regionalhighway_notrace](https://cloud.githubusercontent.com/assets/4990708/6477755/4a6b456c-c1f5-11e4-9345-23f8f8695968.PNG)
![regionalhighway](https://cloud.githubusercontent.com/assets/4990708/6477757/4d91f042-c1f5-11e4-8b0f-74d2682ff093.PNG)

**Comment by Geocruizer** [comment]
![zillaroads](https://cloud.githubusercontent.com/assets/4990708/6477820/f18cd392-c1f5-11e4-9cb6-c2130097457d.PNG)
![zillaroads_notrace](https://cloud.githubusercontent.com/assets/4990708/6477821/f6e5187c-c1f5-11e4-9519-ec1db2902068.PNG)

**Comment by Geocruizer** [comment]
![regionalhghwy](https://cloud.githubusercontent.com/assets/4990708/6478041/b88fe9c8-c1f8-11e4-88e0-264cb9bea612.PNG)
![regionalhghwy_notrace](https://cloud.githubusercontent.com/assets/4990708/6478043/bae49ef8-c1f8-11e4-9272-daf36e2f1389.PNG)

**Comment by mikelmaron** [comment]
all of these images have been added to the repo

https://github.com/hotosm/tracing-guides/tree/gh-pages/images/

**Comment by Geocruizer** [comment]
![img_0726](https://cloud.githubusercontent.com/assets/4990708/6589937/0855417a-c77f-11e4-9d05-8c346ef91207.JPG)
![img_0756](https://cloud.githubusercontent.com/assets/4990708/6589946/2bbda490-c77f-11e4-8fff-c95a92112bcf.JPG)
![road_khulnajessor](https://cloud.githubusercontent.com/assets/4990708/6589958/638dc346-c77f-11e4-832c-7c0d8326d210.jpg)
![img_0659](https://cloud.githubusercontent.com/assets/4990708/6589965/7485f13c-c77f-11e4-9172-6646166b1e62.JPG)
![img_0720](https://cloud.githubusercontent.com/assets/4990708/6589966/8573a8b8-c77f-11e4-9281-3376496a7a13.JPG)

**Comment by Geocruizer** [comment]
![bangladeshnationalhighway](https://cloud.githubusercontent.com/assets/4990708/6731892/9ca252aa-ce1e-11e4-8b91-2ace060e2bfd.jpg)

**Comment by Geocruizer** [comment]
![bangladeshregionalhighway](https://cloud.githubusercontent.com/assets/4990708/6731901/acb48f8c-ce1e-11e4-8c97-b751ba01c39f.png)

**Comment by Geocruizer** [comment]
![bangladeshlinearriver](https://cloud.githubusercontent.com/assets/4990708/6735589/7cc18070-ce35-11e4-8478-20c80f9af08d.png)
![bangladeshlinearriver_notrace](https://cloud.githubusercontent.com/assets/4990708/6735600/89df26fe-ce35-11e4-8b38-6daf23ca3502.png)

**Comment by Geocruizer** [comment]
![riverconfluence](https://cloud.githubusercontent.com/assets/4990708/6740857/948a8b56-ce59-11e4-9e83-ece52df86009.JPG)

**Comment by Geocruizer** [comment]
adds river confluence pic

**Comment by Geocruizer** [comment]
![tertiaryroad](https://cloud.githubusercontent.com/assets/4990708/6758299/7bb04d0a-cf0d-11e4-8aa1-defc7ed6cd0f.jpg)
![zillaroad2](https://cloud.githubusercontent.com/assets/4990708/6758272/54aa83ce-cf0d-11e4-95f8-1b8f8dc89808.jpg)

**Comment by Geocruizer** [comment]
![brickkiln_trace](https://cloud.githubusercontent.com/assets/4990708/6807519/4a78a8d4-d225-11e4-9844-2ed5123bb490.PNG)
![brickkiln](https://cloud.githubusercontent.com/assets/4990708/6807518/4a76f8e0-d225-11e4-870c-197f573d92e6.PNG)
![brickfacories-dhaka-bangladesh-24](https://cloud.githubusercontent.com/assets/4990708/6807539/6f024200-d225-11e4-9ea7-70da435e561b.jpg)

**Comment by Geocruizer** [comment]
![roadunclassified](https://cloud.githubusercontent.com/assets/4990708/6808867/0b85f110-d22d-11e4-9dfc-826d03990b5f.PNG)
![roadunclassified_trace](https://cloud.githubusercontent.com/assets/4990708/6808868/0b8b22e8-d22d-11e4-8591-6c5e7b1905ad.PNG)
![ruralroadbangladesh](https://cloud.githubusercontent.com/assets/4990708/6808960/92c23b20-d22d-11e4-8965-4175b2e5f3ca.jpg)
