### ISSUE TITLE
serving this locally

### ISSUE THREAD

**Issue by wuhland** [hotosm/tracing-guides#22]
I'm having some trouble hosting this locally. I've installed bundler ruby etc as per instructions here: https://help.github.com/articles/using-jekyll-with-pages/ and no error message when I serve but pages are not found. Suspect this has something to do with the fact that this is on gh-pages branch as I've never had issues before but was pushing to a master branch. Might just need to chacnge something in _config. Wondering if anybody is hosting locally and if they had to do anything after cloning to make it work correctly?

**Comment by mikelmaron** [comment]
@wuhland looks like you sorted this out, but can you share the solution in case anyone else gets stuck on this?

**Comment by wuhland** [comment]
@pjdufour showed the way. Not sure if this is going to be helpful as I still don't fully understand why it wasnt working. Expected it to be served here: localhost:4000/tracing-guide dufour suggested I look for it here: 127.0.0.1:4000/tracing-guide and there it is. Still kinda confused because localhost should be resolving to 127.0.0.1 as per normal and also according to /etc/hosts? strange.
