### ISSUE TITLE
QA reverse engineering of Kulna Guide

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/tracing-guides#26]
I think everything is now working at 
http://hotosm.github.io/tracing-guides/guide/kulna.html

Can you double check this @Geocruizer @mnajarro ?

One thing I figured out is the grid layout for 3 images on both odd and even rows.

**Comment by mnajarro** [comment]
Thanks Mikel. This looks awesome. @mnajarro https://github.com/mnajarro is
correct for me.

We still have some content to add in. I'm guessing I can edit directly to
this or create a pull request from the fork I created? (sorry still kind of
new to github)

Mayro

On Wed, Mar 11, 2015 at 9:32 AM, Mikel Maron notifications@github.com
wrote:

> I think everything is now working at
> http://hotosm.github.io/tracing-guides/guide/kulna.html
> 
> Can you double check this @Geocruizer https://github.com/Geocruizer
> @mnajarro https://github.com/mnajarro ?
> 
> One thing I figured out is the grid layout for 3 images on both odd and
> even rows.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hotosm/tracing-guides/issues/26.

## 

Mayro O. Najarro
GeoCenter
US Global Development Lab
USAID
Direct: Ext 20801, Cell: 571-215-3247

**Comment by mikelmaron** [comment]
@mnajarro ... best plan is to fork this repo directly, and make pull requests. most likely will be able to merge without any further work.

**Comment by d3netxer** [comment]
the guide looks awesome!!

**Comment by mnajarro** [comment]
Hey Mikell,

We want to add a new tip to the guide. I am trying to figure out how the
guide is calling only our specific Khulna tips from the _posts/tips folder.
I would like it to bring in our new tip and also order them by water
features and road features. Let me know if you can help with this.

Thanks,
Mayro

On Wed, Mar 11, 2015 at 12:00 PM, Tom G notifications@github.com wrote:

> the guide looks awesome!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hotosm/tracing-guides/issues/26#issuecomment-78293192
> .

## 

Mayro O. Najarro
GeoCenter
US Global Development Lab
USAID
Direct: Ext 20801, Cell: 571-215-3247

**Comment by mikelmaron** [comment]
@mnajarro add the tip "tipid", to the list of "tips" in the yaml frontmatter of the Kulna guide.

Make sense?

What is the new tip you want to add?

**Comment by mnajarro** [comment]
Thanks Mikel. Yeah it makes sense I didn't see it the first time around.
I've made some of the changes.

On Thu, Mar 19, 2015 at 12:50 PM, Mikel Maron notifications@github.com
wrote:

> @mnajarro https://github.com/mnajarro add the tip "tipid", to the list
> of "tips" in the yaml frontmatter of the Kulna guide.
> 
> Make sense?
> 
> What is the new tip you want to add?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hotosm/tracing-guides/issues/26#issuecomment-83659593
> .

## 

Mayro O. Najarro
GeoCenter
US Global Development Lab
USAID
Direct: Ext 20801, Cell: 571-215-3247
