### ISSUE TITLE
Nepal Earthquake tracing guides: discussion

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tracing-guides#49]
so this guide got started by @CmdrKerfy I presume: http://hotosm.github.io/tracing-guides/guide/Nepal.html

I think it would be worth it to have multiple Nepal tracing guides. Or at least 2.

-One for pre-disaster imagery mapping projects (any volunteers?). It would probably involve translating the current instructions to one. However, we should ask whoever set-up the existing projects if they would like one or not.

-One for pre-disaster/post-disaster imagery mapping projects. Depending on how this is planned, it may be better to have more than one guide for these types of projects.

**Comment by Geocruizer** [comment]
![idp_settlement-notrace](https://cloud.githubusercontent.com/assets/4990708/7361874/d0dd18fa-ed2e-11e4-9177-db54f862ddd8.JPG)
![idp_settlement](https://cloud.githubusercontent.com/assets/4990708/7361875/d0deced4-ed2e-11e4-99ec-3ec5c58139d5.JPG)
![ktm-camps-afp](https://cloud.githubusercontent.com/assets/4990708/7361892/0b1c4c16-ed2f-11e4-8a73-7ef2c5ac6ae3.jpg)

**Comment by Geocruizer** [comment]
![idp_tent-notrace](https://cloud.githubusercontent.com/assets/4990708/7362463/3998bcde-ed37-11e4-9ed2-3fb80fa6b184.JPG)
![idp_tent](https://cloud.githubusercontent.com/assets/4990708/7362466/3d9ec53a-ed37-11e4-9030-e187cca2de67.JPG)
![ktmtent](https://cloud.githubusercontent.com/assets/4990708/7362471/461295fc-ed37-11e4-94cf-58f79f45f774.jpg)

**Comment by Geocruizer** [comment]
adds IDP tent

**Comment by Geocruizer** [comment]
![idptents-notrace](https://cloud.githubusercontent.com/assets/4990708/7377469/891ce726-edb4-11e4-8710-16a6a7693ab2.JPG)
![idptents](https://cloud.githubusercontent.com/assets/4990708/7377470/893e03ac-edb4-11e4-84fd-1b4bd5278768.JPG)

**Comment by Geocruizer** [comment]
![idpsettlement-notrace](https://cloud.githubusercontent.com/assets/4990708/7395463/042b962a-ee68-11e4-8b06-2d4fe448f7c8.JPG)
![idpsettlement](https://cloud.githubusercontent.com/assets/4990708/7395464/042dfbf4-ee68-11e4-8b76-c2de6267c226.JPG)

**Comment by Geocruizer** [comment]
![idpsettlement_1](https://cloud.githubusercontent.com/assets/4990708/7395641/341cfefe-ee69-11e4-81d8-d674ffd50fb5.JPG)

**Comment by Geocruizer** [comment]
![idptents_before](https://cloud.githubusercontent.com/assets/4990708/7397620/acdee74a-ee77-11e4-90d4-b6ed035317cf.JPG)
![idptents_after](https://cloud.githubusercontent.com/assets/4990708/7397621/acdfbcce-ee77-11e4-9bd4-8ee652c3292a.JPG)

**Comment by d3netxer** [comment]
![nepal-cropped](https://cloud.githubusercontent.com/assets/2665840/7446719/c92a0cbe-f1af-11e4-8db8-0a3140d92edf.jpg)
