### ISSUE TITLE
Tweaking Tracing Guide Page

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tracing-guides#64]
-Add column that displays file name of tips
-create a tip layout to preview Tips better

**Comment by CmdrKerfy** [comment]
I was going to bring this up at the next Institutions meeting. While helping make the guides for all the events, it seemed that we'd outgrown the template. I was hoping to get feedback from users from GeoWeek to see what they liked and wanted improved.

**Comment by d3netxer** [comment]
sounds good, well I'm almost done implementing these two things. I was having a hard time finding the right tips when making the Piura guide now, because there are so many tips, but having the filename should help that.

**Comment by d3netxer** [comment]
ah, that's better, also made table sortable
